### PR TITLE
add proposal

### PR DESCRIPTION
**Pull request by DianaDai426**
team 19 - create proposal

### CODE REVIEW

**Review by Jiawei-Yang — CHANGES_REQUESTED** [review]
Your post format is incorrect. Please double-check it with other students' posts.

You should have something like this:
```
---
layout: post
comments: true
title: Single Image Super Resolution
author: Ethan Truong, Archisha Datta
date: 2022-01-28
---
```

and do not delete the line of `<!--more-->` from the md file.

**Comment by DianaDai426** [comment]
updated!

**Review by Jiawei-Yang — APPROVED** [review]
LGTM

**Comment by Jiawei-Yang** [comment]
> updated!

Approved and Merged. TY

**Pull request merged**
